---
osie-test-env: &osie-test-env
  image: osie-test-env:${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA:0:8}

clone:
  git:
    image: quay.io/packet/drone-git
    tags: true
    pull: true

pipeline:
  build_osie_test_env_image:
    image: docker
    commands:
      - docker build -t osie-test-env:${DRONE_BUILD_NUMBER}-${DRONE_COMMIT_SHA:0:8} ci
      - mkdir build
      - touch build/osie-test-env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  avoid-builing-alpine-files:
    image: alpine
    commands:
      - ./installer/alpine/skip-building-alpine-files

  ci-checks:
    image: nixos/nix:2.3.4
    group: ci1
    commands:
      - ./ci-checks.sh

  osie_runner_pytest:
    image: python:3.6-alpine
    group: ci1
    commands:
      - pip install dpath==1.5.0 faker pytest pytest-cov
      - cd osie-runner
      - pytest -vv --cov=./

  build_discover_metal:
    <<: *osie-test-env
    group: ci1
    commands:
      - make V=1 T=1 build/discover-metal-x86_64.tar.gz
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  build_aarch64:
    <<: *osie-test-env
    group: ci1
    commands:
      - make V=1 T=1 build/osie-aarch64.tar.gz
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  build_x86_64:
    <<: *osie-test-env
    group: ci1
    commands:
      - make V=1 T=1 build/osie-x86_64.tar.gz
      - make V=1 T=1 build/osie-runner-x86_64.tar.gz
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  osie_scripts_test:
    <<: *osie-test-env
    group: ci1
    commands:
      - find docker/tests -executable -name 'test_*.sh' -execdir {} ';'

  generate_coverage_xml:
    <<: *osie-test-env
    commands:
      - coverage combine osie-runner/.coverage
      - coverage report
      - coverage xml

  package_common:
    <<: *osie-test-env
    commands:
      - make -j$(nproc) package-common

  package:
    <<: *osie-test-env
    commands:
      - make -j$(nproc) package
    when:
      event:
        - push
        - tag

  upload:
    <<: *osie-test-env
    commands:
      - set -v +x
      - mc config host add s3 'https://s3.amazonaws.com' "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" --api s3v4
      - set +v -x
      - echo "$AWS_ACCESS_KEY_ID" | sha256sum
      - echo "$AWS_SECRET_ACCESS_KEY" | sha256sum
      - make deploy
    when:
      event:
        - push
        - tag
    secrets:
      - aws_access_key_id
      - aws_secret_access_key

  upload-pr:
    <<: *osie-test-env
    commands:
      - set -v +x
      - mc config host add s3 'https://s3.amazonaws.com' "$AWS_ACCESS_KEY_ID" "$AWS_SECRET_ACCESS_KEY" --api s3v4
      - set +v -x
      - echo "$AWS_ACCESS_KEY_ID" | sha256sum
      - echo "$AWS_SECRET_ACCESS_KEY" | sha256sum
      - make deploy
    when:
      event:
        - pull_request
    secrets:
      - source: public_aws_access_key_id
        target: aws_access_key_id
      - source: public_aws_secret_access_key
        target: aws_secret_access_key

  test_aarch64_vm:
    <<: *osie-test-env
    group: test
    privileged: true
    commands:
      - OSES=ubuntu_16_04 make V=1 T=1 UEFI=true test-aarch64

  test_x86_64_vm:
    <<: *osie-test-env
    group: test
    privileged: true
    commands:
      - OSES=ubuntu_16_04 make V=1 T=1 test-x86_64
