# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hegel.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name="hegel.proto",
    package="hegel",
    syntax="proto3",
    serialized_pb=_b(
        '\n\x0bhegel.proto\x12\x05hegel"\x0c\n\nGetRequest"\x1b\n\x0bGetResponse\x12\x0c\n\x04JSON\x18\x01 \x01(\t"\x1e\n\x10SubscribeRequest\x12\n\n\x02ID\x18\x01 \x01(\t"!\n\x11SubscribeResponse\x12\x0c\n\x04JSON\x18\x01 \x01(\t2w\n\x05Hegel\x12,\n\x03Get\x12\x11.hegel.GetRequest\x1a\x12.hegel.GetResponse\x12@\n\tSubscribe\x12\x17.hegel.SubscribeRequest\x1a\x18.hegel.SubscribeResponse0\x01\x62\x06proto3'
    ),
)

_GETREQUEST = _descriptor.Descriptor(
    name="GetRequest",
    full_name="hegel.GetRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=22,
    serialized_end=34,
)

_GETRESPONSE = _descriptor.Descriptor(
    name="GetResponse",
    full_name="hegel.GetResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="JSON",
            full_name="hegel.GetResponse.JSON",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=36,
    serialized_end=63,
)

_SUBSCRIBEREQUEST = _descriptor.Descriptor(
    name="SubscribeRequest",
    full_name="hegel.SubscribeRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="ID",
            full_name="hegel.SubscribeRequest.ID",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=65,
    serialized_end=95,
)

_SUBSCRIBERESPONSE = _descriptor.Descriptor(
    name="SubscribeResponse",
    full_name="hegel.SubscribeResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="JSON",
            full_name="hegel.SubscribeResponse.JSON",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
            file=DESCRIPTOR,
        )
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=97,
    serialized_end=130,
)

DESCRIPTOR.message_types_by_name["GetRequest"] = _GETREQUEST
DESCRIPTOR.message_types_by_name["GetResponse"] = _GETRESPONSE
DESCRIPTOR.message_types_by_name["SubscribeRequest"] = _SUBSCRIBEREQUEST
DESCRIPTOR.message_types_by_name["SubscribeResponse"] = _SUBSCRIBERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetRequest = _reflection.GeneratedProtocolMessageType(
    "GetRequest",
    (_message.Message,),
    dict(
        DESCRIPTOR=_GETREQUEST,
        __module__="hegel_pb2"
        # @@protoc_insertion_point(class_scope:hegel.GetRequest)
    ),
)
_sym_db.RegisterMessage(GetRequest)

GetResponse = _reflection.GeneratedProtocolMessageType(
    "GetResponse",
    (_message.Message,),
    dict(
        DESCRIPTOR=_GETRESPONSE,
        __module__="hegel_pb2"
        # @@protoc_insertion_point(class_scope:hegel.GetResponse)
    ),
)
_sym_db.RegisterMessage(GetResponse)

SubscribeRequest = _reflection.GeneratedProtocolMessageType(
    "SubscribeRequest",
    (_message.Message,),
    dict(
        DESCRIPTOR=_SUBSCRIBEREQUEST,
        __module__="hegel_pb2"
        # @@protoc_insertion_point(class_scope:hegel.SubscribeRequest)
    ),
)
_sym_db.RegisterMessage(SubscribeRequest)

SubscribeResponse = _reflection.GeneratedProtocolMessageType(
    "SubscribeResponse",
    (_message.Message,),
    dict(
        DESCRIPTOR=_SUBSCRIBERESPONSE,
        __module__="hegel_pb2"
        # @@protoc_insertion_point(class_scope:hegel.SubscribeResponse)
    ),
)
_sym_db.RegisterMessage(SubscribeResponse)

_HEGEL = _descriptor.ServiceDescriptor(
    name="Hegel",
    full_name="hegel.Hegel",
    file=DESCRIPTOR,
    index=0,
    options=None,
    serialized_start=132,
    serialized_end=251,
    methods=[
        _descriptor.MethodDescriptor(
            name="Get",
            full_name="hegel.Hegel.Get",
            index=0,
            containing_service=None,
            input_type=_GETREQUEST,
            output_type=_GETRESPONSE,
            options=None,
        ),
        _descriptor.MethodDescriptor(
            name="Subscribe",
            full_name="hegel.Hegel.Subscribe",
            index=1,
            containing_service=None,
            input_type=_SUBSCRIBEREQUEST,
            output_type=_SUBSCRIBERESPONSE,
            options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_HEGEL)

DESCRIPTOR.services_by_name["Hegel"] = _HEGEL

# @@protoc_insertion_point(module_scope)
